
- name: Use version for kubernetes < 1.19  
  include_tasks: main_v1.yml
  when: topolvm_version == "0.5.2" or topolvm_version == "0.5.3" or topolvm_version == "0.7.0x"
  
- name: Use version for kubernetes >= 1.19  
  include_tasks: main_v2.yml
  when: topolvm_version == "0.7.0" or topolvm_version == "0.8.3"

- name: Use version for kubernetes >= 1.19
  include_tasks: main_v3.yml
  when: topolvm_version == "0.12.0"